version: "3"
services:
  client1:
    build:
      context: ./Client1
      args:
        dist_ip: 127.0.1.1
        channel: 1
        bs_id: 345
    network_mode: "host"
      
  client2:
    build:
      context: ./Client1
      args:
        dist_ip: 127.0.1.1
        channel: 2
        bs_id: 678
    network_mode: "host"

